<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87817" started-at="2020-11-06T11:58:07Z" finished-at="2020-11-06T11:59:35Z">
    <groups>
      <group name="Login">
        <method signature="A_LoginPageE2E_Test.verfyLoginPageDisplayed()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="verfyLoginPageDisplayed" class="a1_Suits.A_LoginPageE2E_Test"/>
        <method signature="A_LoginPageE2E_Test.Login()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="Login" class="a1_Suits.A_LoginPageE2E_Test"/>
      </group> <!-- Login -->
    </groups>
    <test name="Default test" duration-ms="87817" started-at="2020-11-06T11:58:07Z" finished-at="2020-11-06T11:59:35Z">
      <class name="a1_Suits.A_LoginPageE2E_Test">
        <test-method status="PASS" signature="setUp()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="setUp" is-config="true" duration-ms="23458" started-at="2020-11-06T11:58:07Z" finished-at="2020-11-06T11:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verfyLoginPageDisplayed()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="verfyLoginPageDisplayed" duration-ms="228" started-at="2020-11-06T11:58:31Z" finished-at="2020-11-06T11:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verfyLoginPageDisplayed -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="tearDown" is-config="true" duration-ms="0" started-at="2020-11-06T11:58:31Z" finished-at="2020-11-06T11:58:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="setUp" is-config="true" duration-ms="38563" started-at="2020-11-06T11:58:31Z" finished-at="2020-11-06T11:59:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Login()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="Login" duration-ms="25505" started-at="2020-11-06T11:59:10Z" depends-on-methods="a1_Suits.A_LoginPageE2E_Test.verfyLoginPageDisplayed" finished-at="2020-11-06T11:59:35Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed..! expected [Create a Story] but found [Create a Stori]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed..! expected [Create a Story] but found [Create a Stori]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at a1_Suits.A_LoginPageE2E_Test.Login(A_LoginPageE2E_Test.java:58)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:a1_Suits.A_LoginPageE2E_Test@4cf777e8]" name="tearDown" is-config="true" duration-ms="2" started-at="2020-11-06T11:59:35Z" finished-at="2020-11-06T11:59:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- a1_Suits.A_LoginPageE2E_Test -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
